version: '3'

services:
  # Redis service for caching and context storage
  redis:
    image: redis:7.2-alpine
    container_name: docmost-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --save 900 1 --loglevel warning --maxmemory 2gb --maxmemory-policy allkeys-lru
    networks:
      - docmost-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 30s
      retries: 5
      start_period: 10s
    restart: unless-stopped

  # PostgreSQL database service
  db:
    image: postgres:16-alpine
    container_name: docmost-postgres
    environment:
      POSTGRES_DB: docmost
      POSTGRES_USER: docmost_user
      POSTGRES_PASSWORD: docmost_secure_password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - docmost-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U docmost_user"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    restart: unless-stopped

networks:
  docmost-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  db_data:
    driver: local
