import { useMemo } from "react";
import {
  Badge,
  Button,
  Card,
  Container,
  Group,
  Stack,
  Text,
  Title,
} from "@mantine/core";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useParams } from "react-router-dom";
import { agentMemoryService } from "@/features/agent-memory/services/agent-memory-service";
import { useAtom } from "jotai";
import { workspaceAtom } from "@/features/user/atoms/current-user-atom";
import { listGoals } from "@/features/goal/services/goal-service";
import { runAgentLoop } from "@/features/agent/services/agent-service";

function renderMemoryContent(content: unknown) {
  if (!content || typeof content !== "object") return null;
  const record = content as Record<string, any>;
  if (typeof record.rawResponse === "string" && record.rawResponse.trim()) {
    return record.rawResponse;
  }
  if (record.plan?.summary) {
    return record.plan.summary as string;
  }
  if (Array.isArray(record.actions) && record.actions.length) {
    return `Actions: ${record.actions.map((action: any) => action.method).join(", ")}`;
  }
  return null;
}

function groupByDay(items: Array<{ timestamp?: string }>) {
  return items.reduce<Record<string, typeof items>>((acc, item) => {
    const date = item.timestamp ? new Date(item.timestamp) : new Date();
    const key = date.toLocaleDateString();
    if (!acc[key]) {
      acc[key] = [];
    }
    acc[key].push(item);
    return acc;
  }, {});
}

export function MemoryInsightsPage() {
  const { spaceId } = useParams<{ spaceId: string }>();
  const [workspace] = useAtom(workspaceAtom);
  const queryClient = useQueryClient();

  const memoriesQuery = useQuery({
    queryKey: ["memory-insights", workspace?.id, spaceId],
    queryFn: () =>
      agentMemoryService.query({
        workspaceId: workspace?.id || "",
        spaceId: spaceId || "",
        limit: 120,
      }),
    enabled: !!workspace?.id && !!spaceId,
  });

  const signalsQuery = useQuery({
    queryKey: ["memory-signals", workspace?.id, spaceId],
    queryFn: () =>
      agentMemoryService.query({
        workspaceId: workspace?.id || "",
        spaceId: spaceId || "",
        tags: ["agent-insight"],
        limit: 30,
      }),
    enabled: !!workspace?.id && !!spaceId,
  });

  const goalsQuery = useQuery({
    queryKey: ["goal-insights", workspace?.id, spaceId],
    queryFn: () =>
      listGoals({
        workspaceId: workspace?.id || "",
        spaceId: spaceId || undefined,
      }),
    enabled: !!workspace?.id && !!spaceId,
  });

  const loopMutation = useMutation({
    mutationFn: () =>
      runAgentLoop({
        spaceId: spaceId || "",
      }),
    onSuccess: () => {
      queryClient.invalidateQueries({ queryKey: ["memory-insights"] });
      queryClient.invalidateQueries({ queryKey: ["memory-signals"] });
      queryClient.invalidateQueries({ queryKey: ["agent-approvals"] });
    },
  });

  const grouped = useMemo(() => {
    const items = memoriesQuery.data || [];
    return groupByDay(items);
  }, [memoriesQuery.data]);

  const groupedEntries = Object.entries(grouped);

  return (
    <Container size="lg" py="xl">
      <Group justify="space-between" mb="md">
        <Title order={2}>Insights</Title>
        <Button
          variant="light"
          onClick={() => loopMutation.mutate()}
          loading={loopMutation.isPending}
          disabled={!spaceId}
        >
          Run autonomy cycle
        </Button>
      </Group>

      <Stack gap="md">
        <Card withBorder radius="md" p="md">
          <Group justify="space-between" mb="sm">
            <Title order={4}>Signals & summaries</Title>
            <Text size="xs" c="dimmed">
              Recent insights generated by the agent
            </Text>
          </Group>
          {signalsQuery.isLoading ? (
            <Text size="sm" c="dimmed">
              Loading insights...
            </Text>
          ) : signalsQuery.data?.length ? (
            <Stack gap="xs">
              {signalsQuery.data.map((item) => (
                <Card key={item.id} withBorder radius="sm" p="sm">
                  <Stack gap={4}>
                    <Group justify="space-between">
                      <Text size="sm" fw={600}>
                        {item.summary || "Insight"}
                      </Text>
                      <Text size="xs" c="dimmed">
                        {item.timestamp
                          ? new Date(item.timestamp).toLocaleString()
                          : ""}
                      </Text>
                    </Group>
                    {item.tags?.length ? (
                      <Group gap={6}>
                        {item.tags.map((tag) => (
                          <Badge key={tag} size="xs" variant="light">
                            {tag}
                          </Badge>
                        ))}
                      </Group>
                    ) : null}
                    {item.content ? (
                      <Text size="sm" c="dimmed">
                        {typeof item.content === "string"
                          ? item.content
                          : "text" in (item.content as Record<string, any>)
                            ? (item.content as { text?: string }).text
                            : ""}
                      </Text>
                    ) : null}
                  </Stack>
                </Card>
              ))}
            </Stack>
          ) : (
            <Text size="sm" c="dimmed">
              No insight memories yet.
            </Text>
          )}
        </Card>

        <Group align="flex-start" grow>
          <Card withBorder radius="md" p="md">
            <Title order={4} mb="sm">
              Goal progress
            </Title>
            {goalsQuery.isLoading ? (
              <Text size="sm" c="dimmed">
                Loading goals...
              </Text>
            ) : goalsQuery.data?.length ? (
              <Stack gap="xs">
                {goalsQuery.data.map((goal) => (
                  <Group key={goal.id} justify="space-between">
                    <Text size="sm">{goal.name}</Text>
                    <Badge size="sm" variant="light">
                      {goal.horizon}
                    </Badge>
                  </Group>
                ))}
              </Stack>
            ) : (
              <Text size="sm" c="dimmed">
                No goals found.
              </Text>
            )}
          </Card>

          <Card withBorder radius="md" p="md">
            <Title order={4} mb="sm">
              Graph explorer
            </Title>
            <Text size="sm" c="dimmed">
              Visual memory graph coming soon. This panel will show connected
              topics, people, and goals.
            </Text>
          </Card>
        </Group>

        <Card withBorder radius="md" p="md">
          <Group justify="space-between" mb="sm">
            <Title order={4}>Timeline</Title>
            <Text size="xs" c="dimmed">
              Activity across memories and events
            </Text>
          </Group>
          {memoriesQuery.isLoading ? (
            <Text size="sm" c="dimmed">
              Loading timeline...
            </Text>
          ) : groupedEntries.length ? (
            <Stack gap="md">
              {groupedEntries.map(([date, entries]) => (
                <Stack key={date} gap="xs">
                  <Text size="xs" fw={600} c="dimmed">
                    {date}
                  </Text>
                  {entries.map((entry) => (
                    <Card key={entry.id} withBorder radius="sm" p="sm">
                      <Stack gap={4}>
                        <Group justify="space-between">
                          <Text size="sm" fw={600}>
                            {entry.summary || "Memory entry"}
                          </Text>
                          <Text size="xs" c="dimmed">
                            {entry.timestamp
                              ? new Date(entry.timestamp).toLocaleTimeString()
                              : ""}
                          </Text>
                        </Group>
                        {entry.tags?.length ? (
                          <Group gap={6}>
                            {entry.tags.map((tag) => (
                              <Badge key={tag} size="xs" variant="light">
                                {tag}
                              </Badge>
                            ))}
                          </Group>
                        ) : null}
                        {entry.content ? (
                          <Text size="sm" c="dimmed">
                            {typeof entry.content === "string"
                              ? entry.content
                              : "text" in (entry.content as Record<string, any>)
                                ? (entry.content as { text?: string }).text
                                : renderMemoryContent(entry.content) || ""}
                          </Text>
                        ) : null}
                      </Stack>
                    </Card>
                  ))}
                </Stack>
              ))}
            </Stack>
          ) : (
            <Text size="sm" c="dimmed">
              No memories recorded yet.
            </Text>
          )}
        </Card>
      </Stack>
    </Container>
  );
}
